log_level: "debug"
colorize: true

inet: "localhost"
port: 1491
tcp_timeout: 300
auth_password: "caster"

search:
  query_limit_default: 1000
  query_limit_maximum: 1000

  suggest_limit_default: 5
  suggest_limit_maximum: 20

  list_limit_default: 5
  list_limit_maximum: 20

  term_index_limit: 16
  popularity_weight: .3

kv:
  path: "./data/store/kv/"
  pool:
    inactive_after: 1900
  database:
    flush_after: 1800
    compress: true
    parallelism: 4
    max_files: 1000
    max_compactions: 2
    target_file_size_base: 32768
    max_flushes: 2
    write_buffer: 131072
    write_ahead_log: false
